// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbCISnCap3Ju2t08_XlNQL0__AGcPwW-s',
    appId: '1:501388421930:web:71899fb113271962044c53',
    messagingSenderId: '501388421930',
    projectId: 'pt-booking-app-6859b',
    authDomain: 'pt-booking-app-6859b.firebaseapp.com',
    storageBucket: 'pt-booking-app-6859b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBtBwJtjvFtE32Z-2-sx7rOjTq4-UWq4Q',
    appId: '1:501388421930:android:e6f26350a253e720044c53',
    messagingSenderId: '501388421930',
    projectId: 'pt-booking-app-6859b',
    storageBucket: 'pt-booking-app-6859b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmjebFye_KLotV59bnX5AZNNvpd-8uCDw',
    appId: '1:501388421930:ios:59758db10203140a044c53',
    messagingSenderId: '501388421930',
    projectId: 'pt-booking-app-6859b',
    storageBucket: 'pt-booking-app-6859b.firebasestorage.app',
    androidClientId: '501388421930-clqtjsfgplcmt8grnr8b0hgl6d16q0qj.apps.googleusercontent.com',
    iosClientId: '501388421930-2irgi4dfqdue5d3hielhj6uimg67ehhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ptbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmjebFye_KLotV59bnX5AZNNvpd-8uCDw',
    appId: '1:501388421930:ios:59758db10203140a044c53',
    messagingSenderId: '501388421930',
    projectId: 'pt-booking-app-6859b',
    storageBucket: 'pt-booking-app-6859b.firebasestorage.app',
    androidClientId: '501388421930-clqtjsfgplcmt8grnr8b0hgl6d16q0qj.apps.googleusercontent.com',
    iosClientId: '501388421930-2irgi4dfqdue5d3hielhj6uimg67ehhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ptbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbCISnCap3Ju2t08_XlNQL0__AGcPwW-s',
    appId: '1:501388421930:web:34c3f98dc762d358044c53',
    messagingSenderId: '501388421930',
    projectId: 'pt-booking-app-6859b',
    authDomain: 'pt-booking-app-6859b.firebaseapp.com',
    storageBucket: 'pt-booking-app-6859b.firebasestorage.app',
  );

}
